### PR TITLE
Use gulp edition of Pattern Lab to initialize Pattern Lab system

### PR DESCRIPTION
**Pull request by jordan-caldwell**
## Summary
This is a fresh branch created to initialize the Pattern Lab system. It was built using Pattern Lab Node - Gulp Edition rather than the standard webpack approach. I have included Jason's source directory that was added in later commits of the first PR. This branch should be feature ready to begin pattern lab development.

Note: The TWIG, JS and SCSS should be ignored and not code reviewed. These are a part of the starter pack and will get removed as needed. 

## Metadata

| Question | Answer |
|----------|--------|
| Did you use a meaningful pull request title? | yes
| Did you apply meaningful labels to the pull request? | no
| Did you perform a self review first? | yes
| Documentation reflects changes? | yes
| Risk level | Low
| Relevant links | https://thinkoomph.jira.com/browse/RIG-37

### CODE REVIEW

**Comment by ben-hamelin** [comment]
A quick review of this looks fine to me, but I'm going to defer to @jpamental

**Comment by jpamental** [comment]
It seems to be building just fine but it doesn't seem to be firing up the PatternLab server (even though it seems to be calling it?)

**Comment by jordan-caldwell** [comment]
> It seems to be building just fine but it doesn't seem to be firing up the PatternLab server (even though it seems to be calling it?)

@jpamental, I've updated the default command to always call patternlab:serve rather than only when a twig file is updated.

**Comment by jpamental** [comment]
This is working just as I'd expect now. Looks good to me!

**Pull request merged**
